### ISSUE TITLE
Expose a method to clear the cache for a given post

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/noddity-butler#7]
Required by https://github.com/ArtskydJ/noddity-render-dom/issues/24

The butler isn't in charge of parsing.  But if some post doesn't parse, consumers need to be able to signal to the butler that it is uncool, and should not be cached in the way that other posts are cached.

This may just require a `clearCache(postName)` method.  Reading the code and sleeping on it could confirm.

**Comment by ArtskydJ** [comment]
<a href="https://github.com/tehshrike/levelup-cache">levelup-cache</a> exposes the `refresh(key, [cb])` method, which in turn is exposed by `noddity-butler` in `refreshPost(post, [cb])`. Perhaps this could be used?

**Comment by TehShrike** [comment]
On parse error (#23) I think we should just clear it, we shouldn't trigger a refresh right away.  Refreshing on a parse error would just cause an infinite refresh loop.

**Comment by ArtskydJ** [comment]
Depends on https://github.com/TehShrike/levelup-cache/issues/5.

**Comment by ArtskydJ** [comment]
Thoughts on the name of the method? Here are a few ideas: `butler.removePost()`, `butler.clearPost()`, `butler.deletePost()`

**Comment by TehShrike** [comment]
maybe `clearPost`?

**Comment by ArtskydJ** [comment]
Should I change the existing PR?

**Comment by TehShrike** [comment]
Published as 2.6.0
